"""add vessel equipment and sensor tables

Revision ID: 3cf41749aae3
Revises: a5a265a5ea6e
Create Date: 2026-10-02 11:00:16.498072

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cf41749aae3"
down_revision: str | Sequence[str] | None = "a5a265a5ea6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vessels",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "equipment",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("vessel_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_equipment_vessel_id", "equipment", ["vessel_id"], unique=False)
    op.create_table(
        "sensors",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("equipment_id", sa.String(length=100), nullable=False),
        sa.Column("measurement_type", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sensors_equipment_id", "sensors", ["equipment_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sensors_equipment_id", table_name="sensors")
    op.drop_table("sensors")
    op.drop_index("ix_equipment_vessel_id", table_name="equipment")
    op.drop_table("equipment")
    op.drop_table("vessels")
    # ### end Alembic commands ###
