"""add vessel equipment and sensor tables

Revision ID: 69ebe765efe8
Revises: a5a265a5ea6e
Create Date: 2026-09-08 17:28:08.911747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69ebe765efe8'
down_revision: Union[str, Sequence[str], None] = 'a5a265a5ea6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_measurements_equipment_measured_at'), table_name='telemetry_measurements')
    op.drop_index(op.f('ix_telemetry_measurements_sensor_measured_at'), table_name='telemetry_measurements')
    op.drop_index(op.f('telemetry_measurements_measured_at_idx'), table_name='telemetry_measurements')
    op.drop_table('telemetry_measurements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_measurements',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('measured_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vessel_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sensor_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('measurement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'measured_at', name=op.f('telemetry_measurements_pkey'))
    )
    op.create_index(op.f('telemetry_measurements_measured_at_idx'), 'telemetry_measurements', [sa.literal_column('measured_at DESC')], unique=False)
    op.create_index(op.f('ix_telemetry_measurements_sensor_measured_at'), 'telemetry_measurements', ['sensor_id', 'measured_at'], unique=False)
    op.create_index(op.f('ix_telemetry_measurements_equipment_measured_at'), 'telemetry_measurements', ['equipment_id', 'measured_at'], unique=False)
    # ### end Alembic commands ###
