"""create telemetry measurements

Revision ID: a5a265a5ea6e
Revises: 
Create Date: 2026-08-01 14:33:28.964280

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5a265a5ea6e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_measurements',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.String(length=100), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=False),
    sa.Column('sensor_id', sa.String(length=100), nullable=False),
    sa.Column('measurement_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), 
              server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'measured_at')
    )
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    op.execute(
        """
        SELECT create_hypertable(
            'telemetry_measurements',
            by_range('measured_at'),
            if_not_exists => TRUE
        )
        """
    )
    op.create_index('ix_telemetry_measurements_equipment_measured_at',
                    'telemetry_measurements', ['equipment_id', 'measured_at'], unique=False)
    op.create_index('ix_telemetry_measurements_sensor_measured_at', 'telemetry_measurements', 
                    ['sensor_id', 'measured_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_measurements_sensor_measured_at',
                  table_name='telemetry_measurements')
    op.drop_index('ix_telemetry_measurements_equipment_measured_at',
                  table_name='telemetry_measurements')
    op.drop_table('telemetry_measurements')
    # ### end Alembic commands ###
